apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: omoknooni/focusonyou:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: AWS_SECRET_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: AWS_REGION
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: S3_BUCKET_NAME
        - name: TABLE_NAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: TABLE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 32000