apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 4
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: jdk17
        image: bangwol08/opensw:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
