apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redmine
spec:
  serviceName: redmine
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      nodeName: ip-192-168-10-108
      containers:
      - name: redmine
        image: redmine:latest
        env:
        - name: REDMINE_DB_MYSQL
          value: mysqldb
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        volumeMounts:
          - name: redmine-vol
            mountPath: /home/redmine
      volumes:
        - name: redmine-vol
          persistentVolumeClaim:
            claimName: redmine-vol-claim