apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      nodeName: ip-192-168-10-108 
      containers:
      - name: redmine
        image: redmine:latest
        env: 
        - name: REDMINE_DB_MYSQL
          value: mysqldb
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password 
