apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-vol
  labels:
    type: nfs
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 192.168.10.17
    path: /share/redmine

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-vol-claim
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Gi
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - nfs