apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  serviceName: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeName: ip-192-168-10-29
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
          name: jenkins
        volumeMounts:
        - name: jenkins-vol
          mountPath: /var/jenkins_home
      volumes: 
        - name: jenkins-vol
          persistentVolumeClaim:
            claimName: jenkins-vol-claim
