apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-vol
  labels:
    type: nfs
spec:
  capacity:
    storage: 3Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 192.168.10.17
    path: /share/jenkins

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-vol-claim
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - nfs
